//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGameClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaySession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaySession()
        {
            this.Players = new HashSet<Player>();
        }
    
        public int Id { get; set; }
        public System.DateTime DatePlayed { get; set; }
        public System.TimeSpan PlayTime { get; set; }
        public int BoardGame_Id { get; set; }
    
        public virtual BoardGame BoardGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
    }
}
